services:
  - type: web
    name: easy-storage-relay
    runtime: docker
    dockerContext: .
    dockerfilePath: ./relay/Dockerfile
    healthCheckPath: /health
    region: singapore
    plan: free
    autoDeployTrigger: commit
